# Generated by Django 5.2.17 on 2026-09-28 20:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tripple Phase Electricals', max_length=160)),
                ('logo', models.FileField(blank=True, upload_to='company/')),
                ('address', models.TextField(default='Address to be updated')),
                ('phone', models.CharField(default='Phone to be updated', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('kra_pin', models.CharField(default='P051777360U', max_length=20)),
                ('payment_details', models.TextField(default='Payment details to be updated')),
                ('terms', models.TextField(default='Terms to be updated')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5)),
            ],
            options={
                'verbose_name': 'company settings',
                'verbose_name_plural': 'company settings',
            },
        ),
    ]
