# Generated by Django 5.2.17 on 2026-09-28 20:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_number_sequences(apps, schema_editor):
    sequence_model = apps.get_model("documents", "DocumentNumberSequence")
    database = schema_editor.connection.alias
    for doc_type in ("quotation", "invoice"):
        sequence_model.objects.using(database).get_or_create(doc_type=doc_type)


def remove_number_sequences(apps, schema_editor):
    sequence_model = apps.get_model("documents", "DocumentNumberSequence")
    sequence_model.objects.using(schema_editor.connection.alias).all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('quotation', 'Quotation'), ('invoice', 'Invoice')], max_length=12, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('quotation', 'Quotation'), ('invoice', 'Invoice')], max_length=12)),
                ('number', models.CharField(blank=True, max_length=16, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=160)),
                ('client_phone', models.CharField(blank=True, max_length=40)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_address', models.TextField(blank=True)),
                ('client_pin', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('apply_vat', models.BooleanField(default=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('converted', 'Converted'), ('unpaid', 'Unpaid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank'), ('cheque', 'Cheque')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='documents.document')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-issue_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.document')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_type', 'issue_date'], name='doc_type_issue_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'issue_date'], name='doc_status_issue_idx'),
        ),
        migrations.RunPython(seed_number_sequences, remove_number_sequences),
    ]
