# Generated by Django 5.2.17 on 2026-09-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='payment_terms',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('approved', 'Approved')], default='cash', max_length=12),
        ),
    ]
